ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: dev
      threads: 1
      keepalives_idle: 0
